name: Continuous Integration
on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: '1.22.5'

    - name: Install dependencies
      run: go get .
      working-directory: ./app

#    - name: Run tests
#      run: go test -v
#      working-directory: ./app

    - name: Run linters
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.60
